# Generated by Django 4.2.6 on 2023-11-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='desconto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.CharField(max_length=255),
        ),
    ]
