# Generated by Django 4.2.5 on 2023-12-01 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioAPP', '0002_livros_aluno_livros_desconto_livros_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='aluno',
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biblioAPP.livros')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimo',
            },
        ),
    ]
